### PR TITLE
Create problem: Ksusha and Array

### PR DESCRIPTION
**Pull request by ashmod**
The problem is that your code has a time complexity due to the nested loops. 
**For an array of size 10^5, this would require up to 10^10 operations, which is too many for a program with a 2-second time limit.**

My proposed solution would be to check for the minimum element in the array, and then check if all the elements are divisible by that minimum element.
If there is a number in the array that divides all numbers, it must divide the minimum element as well.

Here is one way to implement it:
```
/*
The problem is that your code has a time complexity due to the nested loops. 
For an array of size 10^5, this would require up to 10^10 operations, which is too many for a program with a 2-second time limit.

My proposed solution would be to check for the minimum element in the array, and then check if all the elements are divisible by that minimum element.
If there is a number in the array that divides all numbers, it must divide the minimum element as well.
*/

#include <iostream>
#include <climits> //this is for the INT_MAX constant
using namespace std;

int main()
{
    const int max_capacity = 10e5;
    int arr[max_capacity];
    int min_element = INT_MAX; //we initalize the min_element to the maximum possible value of an integer so that later, we can replace it with the minimum element in the array :)
    bool isDivisible = true; //this is the flag in your interpretation

    int actual_size;
    cin >> actual_size;

    for (int i = 0; i < actual_size; i++) {
        cin >> arr[i];
        if (arr[i] < min_element) {
            min_element = arr[i];
        }
    }

    for (int i = 0; i < actual_size; i++) {
        if (arr[i] % min_element != 0) {
            isDivisible = false;
            break;
        }
    }

    if (isDivisible) {
        cout << min_element;
    }
    else {
        cout << -1;
    }

    return 0;
}
```
Feel free to ask follow-ups. Good luck coding!

### CODE REVIEW

**Comment by ghost** [comment]
It takes long time to find your comment, thank you shehab for your helping but may you simlify the explanation a little more because i didn't get what you want to do.. if you don't have the time to do so, feel free not to reply... i'll reread it in another time..

**Comment by ghost** [comment]
I think i begin to understand what you meant to do, 
For the division to give integer number the numenerator must be greater than the denomenator, so you get the minimum nuber and chech its condition only, not as i made check for each element, right?
But the last edit for my code was to check this condition before entering the loop of division so i thought cheking the condition is less im time than taking modules of numbers
Thanks a lot for your help

**Comment by dizzydroid** [comment]
No worries, github can be difficult to navigate. Yep, you're getting there..
**Basically your code is flawless as a solution for the problem _but in case of CodeForces_, the website implements a time limit which is the reason why it doesn't run through all the tests,** the reason behind the time limits exceeding is because it checks every possible number in the denominator from the array which takes too long for the program, so a more efficient proposal would be to **make the program check only for the minimum number in the denominator since it must divide all other numbers**.. Here is a code similar to the one on yours with this simple change:
```
#include <iostream>
using namespace std;

int main()
{
    const int max_capacity= 10e5;
    int arr[max_capacity];
    int flag=1;
    int actual_size;
    cin >> actual_size;

    // Read the array
    for(int i=0; i<actual_size; i++)
        cin >> arr[i];

    // Find the smallest number
    int min_num = arr[0];
    for(int i=1; i<actual_size; i++)
    {
        if(arr[i] < min_num)
            min_num = arr[i];
    }

    // Check if min_num divides all other numbers
    for(int i=0; i<actual_size; i++)
    {
        if(arr[i] % min_num != 0)
        {
            flag=0;
            break;
        }
    }

    // If min_num divides all numbers, print it, otherwise print -1
    if(flag)
        cout << min_num;
    else
        cout << -1;

    return 0;
}
```
hope it helps, feel free to ask follow-ups. Good luck!

**Comment by ghost** [comment]
i got it now, thank you for your help!
one last question, 
i know that this ideal code is a reason for long experience in the field of programming.. actually i just want to know a little of them, so my question is how?? i think your answer will be practicing but in my humble opinion this will take a life time without a mentor.. so do u have other suggestions, reading codes from specific references or sth like that??
i'll say it to you again,  if you don't have the time to answer me, feel free not to reply

**Comment by dizzydroid** [comment]
no problem at all, there is no _ideal _code__ in programming, it's all different approaches and they're all great, the best code is the one that can be read by someone who doesn't know anything about coding at all and still manages to understand it :D! (_for example, my first approach in this code wasn't rly ideal because it used unneccessary elements_)

It won't really take that much time, i recommend the following:
- [Codecademy](https://www.codecademy.com/): A website that offers free **interactive** coding courses in different languages 
here's the C++ course page: https://www.codecademy.com/courses/learn-c-plus-plus/lessons/cpp-hello-world
it acts as an interactive reference, you read snippets and you apply them into a compiler alongside. so it's a good step-by-step help.
- [Sololearn](https://www.sololearn.com/profile): Another great website that offers free courses and helps move at the time pace you choose, they have a mobile app too i believe.
- [Youtube](https://www.youtube.com/) is loaded with videos explaining different aspects of the languages, a personal favorite is Harvard's CS50

Personally, i think it's best to keep practicing on CodeForces too, they have good, varied problemsets that will surely help. Certainly, it won't be easy to get the answer on first try, but the trials help strengthen your skills. _**Always**_, search the web when you face errors and see others with similar issues. Make a folder on your PC, dedicated to programming exercises and always try to challenge yourself with tasks just for fun (ex.: i'd like to make a weather app using c++, is this possible?), you'll automatically find yourself searching the web and using different languages,too! You don't need to always accomplish the task but you'll be learning.

Also, there is no "bad questions", always ask and search for questions online. its how we learn. Good luck!

**Comment by ghost** [comment]
Very grateful for you.. shokraaan

**Comment by dizzydroid** [comment]
Anytime, happy to help.. El3afo ^^

**Pull request closed without merging**
